name: localizer
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.0+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  flutter_map: ^0.8.2
  carousel_slider: ^1.3.0
  http: ^0.11.3
  geolocator: ^5.1.5
  app_settings: ^4.0.4
  permission_handler: ^4.0.0
  fluttertoast: ^3.1.0
  cached_network_image: ^2.0.0-rc
  card_settings: ^1.6.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"
flutter_icons:
  android: true
  ios: true
  image_path: "images/splash/splash.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/searchLocation.png
    - images/house.png
    - images/hospital.png
    - images/bank.png
    - images/hotel.png
    - images/store.png
    - images/school.png
    - images/sunrise.png
    - images/sunset.png
    - images/temp.png
    - images/date.png
    - images/humidity.png
    - images/wind.png
    - images/pressure.png
    - images/description.png
    - images/splash/splash.png
    - images/drawerHeader.jpg
    # Day Wallpaper
    - images/weatherMain/01d.jpg
    - images/weatherMain/02d.jpg
    - images/weatherMain/03d.jpg
    - images/weatherMain/04d.jpg
    - images/weatherMain/10d.jpg
    - images/weatherMain/13d.jpg
    - images/weatherMain/50d.jpg
    # Night Wallpaper
    - images/weatherMain/01n.jpg
    - images/weatherMain/02n.jpg
    - images/weatherMain/03n.jpg
    - images/weatherMain/04n.jpg
    - images/weatherMain/10n.jpg
    - images/weatherMain/13n.jpg
    - images/weatherMain/50n.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages